# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: column_profiler.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'column_profiler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63olumn_profiler.proto\x12\x18\x63om.amazon.deequ.connect\x1a\x0c\x63ommon.proto\"\xa9\x03\n\x1b\x44\x65\x65quColumnProfilerRelation\x12\x16\n\x0einput_relation\x18\x01 \x01(\x0c\x12\x1b\n\x13restrict_to_columns\x18\x02 \x03(\t\x12\x30\n#low_cardinality_histogram_threshold\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x1c\n\x14\x65nable_kll_profiling\x18\x04 \x01(\x08\x12?\n\x0ekll_parameters\x18\x05 \x01(\x0b\x32\'.com.amazon.deequ.connect.KLLParameters\x12\x64\n\x10predefined_types\x18\x06 \x03(\x0b\x32J.com.amazon.deequ.connect.DeequColumnProfilerRelation.PredefinedTypesEntry\x1a\x36\n\x14PredefinedTypesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42&\n$_low_cardinality_histogram_thresholdB\"\n\x1e\x63om.amazon.deequ.connect.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'column_profiler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.amazon.deequ.connect.protoP\001'
  _globals['_DEEQUCOLUMNPROFILERRELATION_PREDEFINEDTYPESENTRY']._loaded_options = None
  _globals['_DEEQUCOLUMNPROFILERRELATION_PREDEFINEDTYPESENTRY']._serialized_options = b'8\001'
  _globals['_DEEQUCOLUMNPROFILERRELATION']._serialized_start=66
  _globals['_DEEQUCOLUMNPROFILERRELATION']._serialized_end=491
  _globals['_DEEQUCOLUMNPROFILERRELATION_PREDEFINEDTYPESENTRY']._serialized_start=397
  _globals['_DEEQUCOLUMNPROFILERRELATION_PREDEFINEDTYPESENTRY']._serialized_end=451
# @@protoc_insertion_point(module_scope)
