# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x18\x63om.amazon.deequ.connect\"\x91\x04\n\tPredicate\x12\x44\n\ncomparison\x18\n \x01(\x0b\x32..com.amazon.deequ.connect.Predicate.ComparisonH\x00\x12:\n\x05range\x18\x0b \x01(\x0b\x32).com.amazon.deequ.connect.Predicate.RangeH\x00\x1aV\n\nComparison\x12\x39\n\x02op\x18\x01 \x01(\x0e\x32-.com.amazon.deequ.connect.Predicate.CompareOp\x12\r\n\x05value\x18\x02 \x01(\x01\x1a%\n\x05Range\x12\r\n\x05lower\x18\x01 \x01(\x01\x12\r\n\x05upper\x18\x02 \x01(\x01\"\xb3\x01\n\tCompareOp\x12\x1a\n\x16\x43OMPARE_OP_UNSPECIFIED\x10\x00\x12\x11\n\rCOMPARE_OP_EQ\x10\x01\x12\x11\n\rCOMPARE_OP_NE\x10\x02\x12\x11\n\rCOMPARE_OP_GT\x10\x03\x12\x11\n\rCOMPARE_OP_GE\x10\x04\x12\x11\n\rCOMPARE_OP_LT\x10\x05\x12\x11\n\rCOMPARE_OP_LE\x10\x06\"\x04\x08\x07\x10\x07*\x12\x43OMPARE_OP_BETWEENB\x06\n\x04\x62odyJ\x04\x08\x01\x10\x02J\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05R\x08operatorR\x02opR\x05valueR\x0blower_boundR\x0bupper_bound\"\xa3\x01\n\rKLLParameters\x12\x18\n\x0bsketch_size\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x1d\n\x10shrinking_factor\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x1e\n\x11number_of_buckets\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\x0e\n\x0c_sketch_sizeB\x13\n\x11_shrinking_factorB\x14\n\x12_number_of_buckets*Y\n\nCheckLevel\x12\x1b\n\x17\x43HECK_LEVEL_UNSPECIFIED\x10\x00\x12\x15\n\x11\x43HECK_LEVEL_ERROR\x10\x01\x12\x17\n\x13\x43HECK_LEVEL_WARNING\x10\x02*\xde\x01\n\x11\x43onstraintRuleSet\x12#\n\x1f\x43ONSTRAINT_RULE_SET_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x43ONSTRAINT_RULE_SET_DEFAULT\x10\x01\x12\x1e\n\x1a\x43ONSTRAINT_RULE_SET_STRING\x10\x02\x12!\n\x1d\x43ONSTRAINT_RULE_SET_NUMERICAL\x10\x03\x12\x1e\n\x1a\x43ONSTRAINT_RULE_SET_COMMON\x10\x04\x12 \n\x1c\x43ONSTRAINT_RULE_SET_EXTENDED\x10\x05\x42\"\n\x1e\x63om.amazon.deequ.connect.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.amazon.deequ.connect.protoP\001'
  _globals['_CHECKLEVEL']._serialized_start=740
  _globals['_CHECKLEVEL']._serialized_end=829
  _globals['_CONSTRAINTRULESET']._serialized_start=832
  _globals['_CONSTRAINTRULESET']._serialized_end=1054
  _globals['_PREDICATE']._serialized_start=43
  _globals['_PREDICATE']._serialized_end=572
  _globals['_PREDICATE_COMPARISON']._serialized_start=186
  _globals['_PREDICATE_COMPARISON']._serialized_end=272
  _globals['_PREDICATE_RANGE']._serialized_start=274
  _globals['_PREDICATE_RANGE']._serialized_end=311
  _globals['_PREDICATE_COMPAREOP']._serialized_start=314
  _globals['_PREDICATE_COMPAREOP']._serialized_end=493
  _globals['_KLLPARAMETERS']._serialized_start=575
  _globals['_KLLPARAMETERS']._serialized_end=738
# @@protoc_insertion_point(module_scope)
